# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4202a7d7e4fdbb478215b2086c029a6704d3bbbe1ff688600d33ac513b04dd83ff1ccad580b2c26111207f7a961cbc7ccb7a420e631056090bd74b343af92641

test:
  secret_key_base: 50bb77dcb136a3771cfafebec36800c35c5f1bba64ca8677bf98d90450a2cb189a39b09c29a08adec0915726f2068792fae89b06815697bd911fb96d932d3179

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
